# Generated by Django 3.2.16 on 2022-12-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_body_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='CommentPost',
        ),
    ]
